spring:
  h2:
    console:
      enabled: true
  application:
    name: Catalog Product Processor
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


file:
  write-path:
    csv: /Users/apple/Desktop
    json: /Users/apple/Desktop
